USE imk_db;

-- Add new reminder tracking columns
ALTER TABLE tasks ADD COLUMN notif_1d TINYINT(1) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN notif_6h TINYINT(1) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN notif_3h TINYINT(1) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN notif_2h TINYINT(1) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN notif_1h TINYINT(1) DEFAULT 0;
